[package]

name = "petgraph"
version = "0.1.5"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "Graph data structure library."
documentation = "http://bluss.github.io/petulant-avenger-graphlibrary/target/doc/petgraph"
repository = "https://github.com/bluss/petulant-avenger-graphlibrary"

keywords = ["container", "data-structure", "graph", "unionfind"]

[lib]

name = "petgraph"

[profile.release]
debug = true

[profile.bench]
debug = true

[dependencies.fixedbitset]

[dev-dependencies.rand]

[features]

test = []
